version: '2'
services:
  cd-server:
    image: gocd/gocd-server:v17.3.0
    container_name: quantum-cd-server
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./godata:/godata
      - ./go-home:/home/go gocd/gocd-server
  cd-agent:
    image: gocd/gocd-agent-alpine-3.5:v17.3.0
    container_name: quantum-cd-agent
    environment:
     GO_SERVER_URL: "http://localhost:8153/go"